def food_pos():
    v = [('The food is awesome', 'positive'),
         ('thanks Marche for the delicious food', 'positive'),
         ('Dan emang beneran enak sih nasi gorengnya', 'positive'),
         ('Suka sama bebek ini', 'positive'),
         ('sambel mentah nya bisa request pedasnya..', 'positive'),
         ('Very good and very delish!!!', 'positive'),
         ('Gokils deh enaknya...', 'positive'),
         ('Highly Recommended', 'positive'),
         ('very good and all the desserts also very good..', 'positive'),
         ('Best hamburger but my favorite are their alfredo or carbonara', 'positive'),
         ('Tempat dessert kelapa yang fresh banget!', 'positive'),
         ('lumayan banyak isi coco pouch nya..', 'positive'),
         ('Paling suka coco pouch rasa honeydew asanya seger bangettt~ bener"" energy potion!', 'positive'),
         ('The broth was quite thick than other ramen resto but the meat was so moist and tender so it well combination', 'positive'),
         ('Surely come again', 'positive'),
         ('So klo mnrt gue dri segi makanan sih lumayan', 'positive'),
         ('Cheese cake nya juara. Lembut.', 'positive'),
         ('As you know Wargih ini selalu rame gapernah sepi', 'positive'),
         ('Best bingsu yg pernah gue coba!', 'positive'),
         ('Paling mirip sama aslinya yg di korea!', 'positive'),
         ('shaved icenya kerasa bgt milknya dan red beannya bukan yg kasar tapi yg halus emang khas koreanya bgt', 'positive'),
         ('Asides from the very tasty', 'positive'),
         ('i must say garcon is offering lots of nice dessert and coffee', 'positive'),
         ('Their macaron taste nice, profiteroles taste good', 'positive'),
         ('And yes,  i once had escargot which also taste good', 'positive'),
         ('untuk rasa kopi nya aku suka banget ya', 'positive'),
         ('tapi menurut temen2 ane, dessertnya enak', 'positive'),
         ('Pilihan menunya banyak banget, mostly enak, and I tried them all! hahaha', 'positive'),
         ('Bebek peking, sate, &amp; dessertnya juara', 'positive'),
         ('it\'s all about 5 star foods, ambience, &amp; service', 'positive'),
         ('They food also tastes good', 'positive'),
         ('The spider roll is nice. It\'s crunchy', 'positive'),
         ('The salmon teriyaki is also good', 'positive'),
         ('Enak', 'positive'),
         ('Nagih', 'positive'),
         ('tp pas dimakan rasanya unik banget', 'positive'),
         ('Crispy diluar dalemnya kenyel2 kaya mochi trus ada choco chipnya semua nyatu banget! ', 'positive'),
         ('dua-dua nya cukup enak untuk pertama kali berkunjung', 'positive'),
         ('Very tasty Indonesian cuisine', 'positive'),
         ('The Nasi Cakalang, Nasi Limo, and Nasi Ayam Pecel are the must-try dishes...', 'positive'),
         ('Secara keseluruhan sih masih boleh lah dimsum di sini dijadikan sasaran untuk brunch atau ngemil iseng', 'positive'),
         ('dengan ciri khas makanan yang lezat dan kualitasnya bagus..', 'positive'),
         ('Shaokaonya enak, bumbunya pas dan dibakarnya juga pas ga terlalu kering..', 'positive'),
         ('very recommended..', 'positive'),
         ('Martabak Pecenongan 65A never disappoints me', 'positive'),
         ('Adonan tebal maupun yg tipis enak""! Topingnya dikasih melimpah', 'positive'),
         ('Good taste overall', 'positive'),
         ('Goreng-goreng enak, lumpia udang kulit tahu suprisingly enak...', 'positive'),
         ('Makanannya juga enak, gue pesen cumi dan bebek dengan nasi hainam super yummy!', 'positive'),
         ('Enak nih,  Chinese food nya', 'positive'),
         ('mantap nasi goreng seafood nya&#128077;', 'positive'),
         ('penasaran ma tuh rrsep nya ,   kaya ada harum kare nya gitu deh..', 'positive'),
         ('Nasi gorengnya enak dan gurih', 'positive'),
         ('Aku pesen steamboat spesial kuah tom yum rasanya enak seger sih kenyang bgt buat makan ber 3 tanpa nasi', 'positive'),
         ('Recommended deh', 'positive'),
         ('Sabar menunggu lama krn dori nya enak sekali', 'positive'),
         ('Paling suka pesan dengan Wedges potato! Ah i\'m in love with this kind of potato &#9825;', 'positive'),
         ('You can choose how will they cook it : butter cooked, sweet and sour, curry, or just boiled it', 'positive'),
         ('Suka sama kopinya, terutama red velvet ice latte-nya enak!', 'positive'),
         ('I love to eat bbq beef burger, very delicious !', 'positive'),
         ('the all day dining menu are pretty decent', 'positive'),
         ('Makanannya lumayan enak. Menunya banyak.', 'positive'),
         ('Overall rasanya enak, next time i\'ll come back', 'positive'),
         ('Nuttela latte nya enak lumayan kental dengan porsi mini, coffee vietnamnya so so lah..', 'positive'),
         ('singkong keju meski kejunya dikit tapi oke lah tertutupi sama tekstur singkongnya yang lembut', 'positive'),
         ('Potato wegess nya enak, recomended la..', 'positive'),
         ('Pilihan tepat klo mau makan steak enak', 'positive'),
         ('rasa maknyus..', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('WOW surprisingly enak enak lho!! Pizzanya apalagi! Truffle-nya pas nggak over powering, crustnya enak tipis tp ga begitu tipis', 'positive'),
         ('Spaghettinya enaaakk al dente dan seasoning garlic and pepper-nya pas', 'positive'),
         ('Honestly, ini uenak banget, kita sampe pesen 2x dan jadinya makan cuma itu doang', 'positive'),
         ('85% suit my taste for their menya gyutan don hehehe it really is my favorite', 'positive'),
         ('but the taste was not really bad, i love it too', 'positive'),
         ('great quality products with a lot of tasty treats to buy and take home, or even share with family/friends', 'positive'),
         ('Cake quality was extremely good', 'positive'),
         ('Kuenya enak rasanya udah sering beli disini juga', 'positive'),
         ('The beef so big and also tasty n juicy..', 'positive'),
         ('i really love with onion rings , the crunchy of the onion is so amazing with the sausage', 'positive'),
         ('Best shabu in town!!!', 'positive'),
         ('Chinese food yang enak terutama menu Sapo Tahu Seafood dan Fu Yung Hai yang menjadi menu favorit setiap makan ke sini', 'positive'),
         ('Huaaa wangi na menggoda banget. Bawang putih na msntaf', 'positive'),
         ('Kepiting na padat. Seger. Empuk. Gurih. Ga berasa makan na sangking enak na', 'positive'),
         ('Capit na jg gede padat berisi. Gua pyas banget sama kepiting na', 'positive'),
         ('semuanya terasa diatas rata rata untuk nasi jeruk menurut saya rasa ayam yang lembut dan bumbu yang meresap membuat makanan ini terasa sangat nikmat.well done', 'positive'),
         ('Taste is nice,but for me it doesn\'t make me wanting to go back there asap..', 'positive'),
         ('Love the food, it comes in a huge portion...', 'positive'),
         ('dari rasa sih enak', 'positive'),
         ('Enjoy the food so much', 'positive'),
         ('Slow braised wagyu / pork belly bun is soooo good', 'positive'),
         ('baksonya so far enak dan lumayan ngenyangin porsinya', 'positive'),
         ('Yang enak tuh disini baksonya di campur potongan kikil yang kenyal2 jadi makan bakso jadi makin seru', 'positive'),
         ('Suki di sini termasuk enak', 'positive'),
         ('Untuk makanan yaaa biasa lah lumayan enak', 'positive'),
         ('untuk rasaanyaa behhh.. enak bgt', 'positive'),
         ('cocok bgt di lidah buat pecinta seafood', 'positive'),
         ('selain karena rasanya yg pas', 'positive'),
         ('I like the shabu2 here', 'positive'),
         ('Just sweet and nice', 'positive'),
         ('Their satay is also quite good. Must try the satay', 'positive'),
         ('Ordered the Kyoto Mathca Kakigori and Matcha Latte and loved it', 'positive'),
         ('Untuk dagingnya saya bilang baik, yang agak minus adalah rasa mushroom sauce', 'positive'),
         ('This dessert is both sweet and refreshing at the same time!', 'positive'),
         ('Rasa bumbu sate nya lumayan', 'positive'),
         ('Dari tiga kali ke sini, dua kali saya pesen Nachos karena keju dan dagingnya yang nyummy', 'positive'),
         ('Rasanya 4/5, karena rada pait dan cepet dingin', 'positive'),
         ('Makanannya enak2 semua, minumannya juga enak dan ada yg bisa untuk share', 'positive'),
         ('Variasi makanannya banyak, rasanya enak', 'positive'),
         ('rasanya lumayan,pilihan menu banyak', 'positive'),
         ('makanan2 di sini berkualitas', 'positive'),
         ('semuanya ok banget.. dan so far gw ga pernah ktm makanan yg ga enak di resto ini', 'positive'),
         ('They pan-fried it really well, not too dry so the kuotie is not too crispy', 'positive'),
         ('Juicy and crispy at the same time', 'positive'),
         ('Pertama order Salmon Triple Flavor..fresh, juicy, beda dengan resto sushi lainnya', 'positive'),
         ('Salmon Garlic Cheese dan Salmon Pollock Roe yum yum..', 'positive'),
         ('California Handroll, Chrispy Spicy Salmon, puncaknya Sashimi Salad enak bangedd', 'positive'),
         ('Suami bilang Green Tea-nya the best in town..overall puass', 'positive'),
         ('Great Fusion Juice', 'positive'),
         ('Taste: 4.5/ 5.0', 'positive'),
         ('Makanannya enak . Minumannya juga segar dan enak', 'positive'),
         ('Good food', 'positive'),
         ('Food was so-so according to my family', 'positive'),
         ('The babyback ribs was pretty delicious, though because the spices seeped into the meat', 'positive'),
         ('the portion of the Pho is generous and taste wise it\'s delicious', 'positive'),
         ('Love the Kumquat Juice, it taste sweet and sour', 'positive'),
         ('Masakanya enak', 'positive'),
         ('Enakkk,pengalaman makan disini cukup menyenangkan', 'positive'),
         ('yang perlu dicobain sebenernya thai ice green teanya! enak banget banget', 'positive'),
         ('semuanya enak enak enak', 'positive'),
         ('Tempat paling nyaman buat bikin bibir dan lidah berasa dingin dan buat otak lumer akibat nikmatnya menu disini', 'positive'),
         ('Taste : 7.5  Look : 7.5', 'positive'),
         ('Takarannya pas bgt buat hot coffee', 'positive'),
         ('Bumbunya enakkk dehh, meski porsi sedikit', 'positive'),
         ('Love this place! I always love healthy food that tastes good', 'positive'),
         ('I ordered the mango sunshine (with granola), and it tastes superb', 'positive'),
         ('Makanannya juga enak sesuai harga', 'positive'),
         ('The niku idon is quite good. The side dish so so imho', 'positive'),
         ('Enakkk dan nagih utk kesini lg', 'positive'),
         ('The buta katsu was tasty, crispy and savory', 'positive'),
         ('Okonomiyaki bacon was good, you can definitely taste the meat and you can feel it crispyness', 'positive'),
         ('aku pesen roti butter sama teh tarik dan rasaanyaa paaaaaaas dimulut [80/100]', 'positive'),
         ('cireng sosis sama mie chibi yang pedes bikin nagih', 'positive'),
         ('Porsinya lumayan besar dan bikin kenyang', 'positive'),
         ('Untuk rasa menurut sayaa enak, nasi briyaninya lembut-lembut gimana gitu', 'positive'),
         ('The best fish and chips in town', 'positive'),
         ('Bener2 enak.Ikannya lembuuuuttt bgt,terus crispy,kentangnya jg juara', 'positive'),
         ('Saya denger disitu mashed potatonya enak,pas saya coba.....ENAK BANGET', 'positive'),
         ('tp over all nasinya enak dan daging prawnnya empuk membal gmn gt hehe', 'positive'),
         ('Soup of the day', 'positive'),
         ('Enak sih.Creamy bgt,sukaa', 'positive'),
         ('Good Food, love the chicken n veggie rice', 'positive'),
         ('You can add on anythig into this stew', 'positive'),
         ('The beer suits  my taste', 'positive'),
         ('Love the pork belly', 'positive')]
    return v


def food_neg():
    v = [('The food varieties arent that many', 'negative'),
         ('Yang agak ngga sreg mungkin cuma western foodnya, somehow berasa biasa aja', 'negative'),
         ('Porsinya sedikit', 'negative'),
         ('Rasanya biasa aja. Overall Tidak worth it', 'negative'),
         ('I wouldn\'t recommend their breakfast menu', 'negative'),
         ('pesen gue kue cubit tuna tapi kurang greget', 'negative'),
         ('pesen susu rasa greentea tapi rasa green tea nya kurang terasa', 'negative'),
         ('Makanan yang saya pesan adalah spaghetti babi, dan rasanya hanya micin + bubuk cabai', 'negative'),
         ('The seasoning was just not there, it was quite plain and boring', 'negative'),
         ('sumpah ini tuh kayak kopi instant sachet yg rasa vanilla, pokoknya ga enak sama sekali', 'negative'),
         ('tapi jujur ini roti pisang bakar paling ga enak yg pernah gua makan', 'negative'),
         ('Setelah pengalaman buruk di Donburi Ichiya LW karena ayamnya gosong hitam', 'negative'),
         ('Sayang kecewa sm gyutandon nya yang malah enakan di LW', 'negative'),
         ('but it\'s not my kinda of ice cream, for me it\'s too sweet', 'negative'),
         ('It was disappointing', 'negative'),
         ('I was truly madly deeply disappointed :( The actual size was faaaaarrrr waaaayyyy smaller than in the picture', 'negative')]
    return v


def price_pos():
    v = [('the price is not worth anymore', 'positive'),
         ('Harga nya bersahabat banget', 'positive'),
         ('I always come here only for the roasted chicken, because the price isn\'t high at all', 'positive'),
         ('Price is super affordable', 'positive'),
         ('i can safely say that you get what u paid for, and that\'s a 5!', 'positive'),
         ('buat harga standar', 'positive'),
         ('Murah', 'positive'),
         ('this is my best pocket friendly place', 'positive'),
         ('harganya sangat terjangkau', 'positive'),
         ('Harga ga terlalu mahal, plus sering ad diskon..', 'positive'),
         ('very recommended..', 'positive'),
         ('Harganya juga pas! Pokoknya the best martabak maker deh', 'positive'),
         ('harga nya juga gak mahal', 'positive'),
         ('lumayan lg ada disc 50% juga hihihihi :D&#160;', 'positive'),
         ('Untuk harga standar buat kantong mahasiswi', 'positive'),
         ('harga pas di kantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga termasuk okelah untuk di lokasi daerah cikini/menteng', 'positive'),
         ('The price says the portion and the tasty..', 'positive'),
         ('Agak mahal tp gua puas', 'positive'),
         ('The price is still alright if you compare to the portion, better come here with friends so you can share the food...', 'positive'),
         ('murah dibanding suki tempat lain', 'positive'),
         ('harganya worth it sih..', 'positive'),
         ('harganya juga pas', 'positive'),
         ('tempat ini sangat terjangkau untuk kalangan mahasiswa yang ingin makan steak dengan harga yang relatif dibawah rata rata', 'positive'),
         ('Harganya standar sih..', 'positive'),
         ('Beer disini termurah se kelapa gading!', 'positive'),
         ('Harganya cukup mahal tapi worth it dengan rasa makanannya', 'positive'),
         ('tapi cukup murah cuma 20 ribu', 'positive'),
         ('Pricing was okay (and rather cheap), quite balanced with the taste', 'positive'),
         ('price average buat level dessert dan gua puas dah', 'positive'),
         ('The portion is quite big and costs around 45k. Totally worth it!', 'positive'),
         ('Makanannya juga enak sesuai harga', 'positive'),
         ('Total cost was only 107k', 'positive'),
         ('Wowww chasiu garing madu nya muantaappppp', 'positive'),
         ('casio madunya top abi', 'positive'),
         ('masakan lainnya jg enak, bebek panggang gak amis n bumbunya nyerep', 'positive'),
         ('Untuk harga cukup affordable 130ribu untuk 2porsi udah plus air mineral dan kentang goreng', 'positive')]
    return v


def price_neg():
    v = [('Decent price (used to be)', 'negative'),
         ('Untuk harga mungkin agak mahal ya', 'negative'),
         ('In overall this place is pricey', 'negative'),
         ('memang harga makanan disini mahal-mahal', 'negative'),
         ('Harganya mahal', 'negative'),
         ('as most of them are overpriced for the portion and quality of the food ', 'negative'),
         ('The price is quite expensive,although the dish can still be enjoyed by 2 people..', 'negative'),
         ('Too bad it is a bit pricey and they even charge for garlic', 'negative'),
         ('btw siapin kocek yg mayan tp ya', 'negative'),
         ('sedikir pricy tentunya', 'negative'),
         ('Soal harga lumayan mahal buat saya', 'negative'),
         ('ga worth it sama harga', 'negative'),
         ('expensive for sure', 'negative'),
         ('ternyata cukup pricey ', 'negative'),
         ('but I expected something more for this price', 'negative')]
    return v


def service_pos():
    v = [('kursinya lumayan banyak ada toilet nya juga..', 'positive'),
         ('also great service that gives you great vibe!', 'positive'),
         ('orang2 disini ramah banget bikin mau kesini teruus', 'positive'),
         ('pelayanan nya ramah banget dan enak untuk diajak ngobrol soal kopi', 'positive'),
         ('Dan service disini sopan banget', 'positive'),
         ('Serving staffnya ramah &amp; fast response', 'positive'),
         ('it\'s all about 5 star foods, ambience, &amp; service', 'positive'),
         ('The waiters are kind to us', 'positive'),
         ('mas nya mau nganter', 'positive'),
         ('Mas mas nya juga ramah', 'positive'),
         ('Plus mereka menampung kritik dan saran di instanya (@martabak65a) atau di contact personnya sendiri', 'positive'),
         ('pelayanannya cepet bgt', 'positive'),
         ('Recommended deh', 'positive'),
         ('Tapi walaupun selalu waiting list tp tidak butuh waktu lama sdh dapat tempat duduk', 'positive'),
         ('Pelayanan nya ramah', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('at first pelayanannya bagus cepet dan friendly', 'positive'),
         ('along with friendly customer service', 'positive'),
         ('Pelayanannya oke punya', 'positive'),
         ('The service was remarkable', 'positive'),
         ('Ambiance and service is also good', 'positive'),
         ('Mas/mbak nya baik. Pelayanan lumayan cepet', 'positive'),
         ('jd bisa dilayani cepat ;)', 'positive'),
         ('servicenya baik kok.. Pelayanannya juga cepat tanggap', 'positive'),
         ('The waitress will be cookig for us and put them on a plate with sesame oil', 'positive'),
         ('Pelayannya ramah2 dan fast response', 'positive'),
         ('pelayanannya oke, ramah, dan selalu siap sedia untuk melayani kita dlm hal menawarkan minuman dan mengangkat piring kotor', 'positive'),
         ('Pelayanan disetiap station makanannya juga ramah, menyenangkan lah makan disini', 'positive'),
         ('Resto ini bersih, canggih dan pelayanannya cukup ok', 'positive'),
         ('best service', 'positive'),
         ('Service: 4.0/5.0', 'positive'),
         ('Pelayanannya baik dan cepat', 'positive'),
         ('Para pelayannya ramah dan baik', 'positive'),
         ('good service', 'positive'),
         ('Servicenya ok, pelayannya ramah', 'positive'),
         ('The service is quick , the servers pretty much answers our question about their menu pretty on point', 'positive'),
         ('Staff nya ok, pelayanan cepet', 'positive'),
         ('kebetulan langsung dapet tanpa waiting list tempat nya mudah di cari pelayanan ramah tempat bikin betah colokan banyak lagi', 'positive'),
         ('the staff were friendly', 'positive')]
    return v


def service_neg():
    v = [('Gilak gue rasa utk servis msh hrs byk belajar deh, gak kyk td pelayannya gak peka', 'negative'),
         ('Masih kaku gt', 'negative'),
         ('Terus masa gue dah hampir 30menit lama gak ada satupun mknan yg dtg', 'negative'),
         ('service dan prosedur pelayanannya sih yg mesti jd concern, kliatan bgt blm ready', 'negative'),
         ('Ditambah pelayananannya lama, harus diingetin dulu baru dibikin', 'negative'),
         ('Selang 1 jam baru makanan diantar, padahal hanya mie kuah', 'negative'),
         ('Too bad for the slooooow service', 'negative'),
         ('VERY LONG service time', 'negative'),
         ('Pelayanannya cukup lama. Bahkan untuk minta bill aja lamanya minta ampun.', 'negative'),
         ('makin lama juga pelayannya gak ramah ,awalnya doang dateng ramah banget mungkin baru buka tapi minggu kemarin gilaaa waitress nya gak peka bngt', 'negative'),
         ('Untuk pelayanan, saya cukup kecewa karena para pekerja joni steak lah yang ribut sendiri', 'negative'),
         ('Mengecewakan pelayanannya. ZONK!!!!', 'negative'),
         ('yg ga nahan itu harus ngantri hampir 1 jam', 'negative'),
         ('One thing that disturb me is the waiting list', 'negative')]
    return v


def ambience_pos():
    v = [('I love the concept', 'positive'),
         ('also the nice place', 'positive'),
         ('I love the concept', 'positive'),
         ('suasana nya juga enak buat makan ramai2 gitu', 'positive'),
         ('Best place to date someone', 'positive'),
         ('Good ambiance nice interior', 'positive'),
         ('Pdhal tempatnya dah keren, luas bgt', 'positive'),
         ('Interiornya keren', 'positive'),
         ('Tempatnya enak, cozy, parkirannya pun lumayan luas', 'positive'),
         ('As you know Wargih ini selalu rame gapernah sepi', 'positive'),
         ('Great concept relatable with its name \'Marche\'', 'positive'),
         ('Good interior', 'positive'),
         ('Tempatnya jg unik bgt lucu bisa buat foto2 hehe', 'positive'),
         ('Nice place to chill with', 'positive'),
         ('try to come here at night its beautiful', 'positive'),
         ('perfect place to spend with family or lover', 'positive'),
         ('Perfect getaway', 'positive'),
         ('ambience is very cosy', 'positive'),
         ('Tempat nya enakk banget nyaman banget', 'positive'),
         ('Tempatnya gede banget, lavish, apalagi yang ada di sayap kiri keren banget buat foto2', 'positive'),
         ('it\'s all about 5 star foods, ambience, &amp; service', 'positive'),
         ('This place is nice', 'positive'),
         ('Well organized', 'positive'),
         ('The ambience of the restaurant is relaxing', 'positive'),
         ('A good place to get a short break during a stressfull day', 'positive'),
         ('Untuk tempat cukup nyaman walau kami merasa tinggi meja dan kursi kurang nyaman untuk makan dikarenakan meja yang pendek', 'positive'),
         ('A small but cozy culinary hideout in South Jakarta', 'positive'),
         ('Tempatnya bersih', 'positive'),
         ('Penyajiannya oke aka higenis', 'positive'),
         ('Great place! Tempatnya nyaman banget, spacious', 'positive'),
         ('Tempatnya enak, nyaman kursinya, walaupun agak kecil sih tp dekorasinya bagus', 'positive'),
         ('Recommended deh', 'positive'),
         ('tempatnya juga cozy dan gak berisik karena posisinya di pojokan', 'positive'),
         ('Love the ambience of this place', 'positive'),
         ('Apalagi yg outdoor, sejuk', 'positive'),
         ('This place isn\'t big but very cozy for me with nice music', 'positive'),
         ('Tempatnya luas sekali', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempatnya lumayan lucu ada indoor dan outdoor (smoking area)', 'positive'),
         ('Great place, lovely ambience', 'positive'),
         ('tempatnya juga cozy banget', 'positive'),
         ('One of the best and also fancy restaurant in jakarta and also overseas ya....', 'positive'),
         ('The venue also romantic, if u take outdoor..', 'positive'),
         ('Dengan lokasi yang strategis pinggir jalan di ruko sebrang UIKA', 'positive'),
         ('Tempatnya menarik sekali,tidak terlalu luas namun bisa menampung banyak orang', 'positive'),
         ('Tempatnya enak buat nongki ngobrol2', 'positive'),
         ('Baru masuk aja udah berasa meksikonya. Mulai dari musik sampe desain interiornya.', 'positive'),
         ('I absolutely loved this rooftop joint. I loved having the whole greenery ambience going on.', 'positive'),
         ('Also, the music was quite great and I would definitely love to come back for many more chilled out late nights', 'positive'),
         ('After few years opens this place still has the same ambience which is good, keep the good work!', 'positive'),
         ('Banyak variasinya ada sushi, tempura, steak, spagethi, dimsum, shabu-shabu, beef teriyaki, salad dll', 'positive'),
         ('Dessertnya super banyak pilihannya juga dan topping eskrim beraneka ragam', 'positive'),
         ('Ambiance and service is also good', 'positive'),
         ('Untuk tempat keren lah nyaman dan bisa liat pemandangan..', 'positive'),
         ('tempatnya biasa aja sangat sederhana, sangat ramai di jam jam makan dan cocok bgt buat restoran keluarga', 'positive'),
         ('Ambience tmptnya okay', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Untuk tempatnya biasa saja tapi nyaman buat ajak keluarga juga', 'positive'),
         ('Stop kontak dan wifi tersedia secara cuma cuma', 'positive'),
         ('Tempatnya enak, nyaman dan cocok untuk romantic dinner even in buffet style', 'positive'),
         ('D\'Consulate memang tempat yang nyaman untuk hang-out', 'positive'),
         ('great decoration. feels like home.. I just love it', 'positive'),
         ('Ambience: 4.0/5.0', 'positive'),
         ('Suasana talaga sampierun terasa sejuk dan tertata rapi', 'positive'),
         ('Fancy place', 'positive'),
         ('good view', 'positive'),
         ('suasana homey, kecil, tp nyaman', 'positive'),
         ('Outdoornya juga bagus, dengan meja kayunya yg catchy, pas buat foto', 'positive'),
         ('Tempat ini recomended bagi saya', 'positive'),
         ('suasana disini lumayan cozy', 'positive'),
         ('Restauran yang satu ini designnya unik', 'positive'),
         ('Dengan ruangan spacious dari building, restoran ini membuat dining areanya tinggi sehingga memberi kesan mewah dan lux', 'positive'),
         ('Tempatnya super cozy, alunan musiknya bikin konsen ngerjain kerjaan', 'positive'),
         ('The place was small and cozy', 'positive'),
         ('the place is cozy', 'positive'),
         ('The place is standard, but okay', 'positive'),
         ('I love the industrial-themed decoration and the place is quite spacious', 'positive')]
    return v


def ambience_neg():
    v = [('The only lack about garcon is their humid smoking area', 'negative'),
         ('diluasin lagi tempatnya untuk smoking area, is to small and hot :(', 'negative'),
         ('soalnya kursinya juga dikit terus gelap', 'negative'),
         ('Tempatnya sebenarnya besar, tapi penataannya nggak terlalu rapi dan ""fit-in"", apalagi di lantai 2 nya', 'negative'),
         ('Suasananya juga berisik', 'negative'),
         ('tapi kalau suka dengan suasana tenang, I don\'t recommend you to eat here', 'negative'),
         ('I didn\'t quite like the interior, it\'s a bit \'meh\' to me', 'negative'),
         ('The place is very small though, but we could sit at bao ji', 'negative'),
         ('But i dont feel comfortable with the air, its too hot', 'negative'),
         ('But I suggest not to eat it when sunny days or you will get sweaty easily because the ac is not that cool', 'negative')]
    return v
