def food_pos():
    v = [('The food is awesome', 'positive'),
         ('thanks Marche for the delicious food', 'positive'),
         ('Dan emang beneran enak sih nasi gorengnya', 'positive'),
         ('Suka sama bebek ini', 'positive'),
         ('sambel mentah nya bisa request pedasnya..', 'positive'),
         ('Very good and very delish!!!', 'positive'),
         ('Gokils deh enaknya...', 'positive'),
         ('Highly Recommended', 'positive'),
         ('very good and all the desserts also very good..', 'positive'),
         ('Best hamburger but my favorite are their alfredo or carbonara', 'positive'),
         ('Tempat dessert kelapa yang fresh banget!', 'positive'),
         ('lumayan banyak isi coco pouch nya..', 'positive'),
         ('Paling suka coco pouch rasa honeydew asanya seger bangettt~ bener"" energy potion!', 'positive'),
         ('The broth was quite thick than other ramen resto but the meat was so moist and tender so it well combination', 'positive'),
         ('Surely come again', 'positive'),
         ('So klo mnrt gue dri segi makanan sih lumayan', 'positive'),
         ('Cheese cake nya juara. Lembut.', 'positive'),
         ('As you know Wargih ini selalu rame gapernah sepi', 'positive'),
         ('Best bingsu yg pernah gue coba!', 'positive'),
         ('Paling mirip sama aslinya yg di korea!', 'positive'),
         ('shaved icenya kerasa bgt milknya dan red beannya bukan yg kasar tapi yg halus emang khas koreanya bgt', 'positive'),
         ('Asides from the very tasty', 'positive'),
         ('i must say garcon is offering lots of nice dessert and coffee', 'positive'),
         ('Their macaron taste nice, profiteroles taste good', 'positive'),
         ('And yes,  i once had escargot which also taste good', 'positive'),
         ('untuk rasa kopi nya aku suka banget ya', 'positive'),
         ('tapi menurut temen2 ane, dessertnya enak', 'positive'),
         ('Pilihan menunya banyak banget, mostly enak, and I tried them all! hahaha', 'positive'),
         ('Bebek peking, sate, &amp; dessertnya juara', 'positive'),
         ('it\'s all about 5 star foods, ambience, &amp; service', 'positive'),
         ('They food also tastes good', 'positive'),
         ('The spider roll is nice. It\'s crunchy', 'positive'),
         ('The salmon teriyaki is also good', 'positive'),
         ('Enak', 'positive'),
         ('Nagih', 'positive'),
         ('tp pas dimakan rasanya unik banget', 'positive'),
         ('Crispy diluar dalemnya kenyel2 kaya mochi trus ada choco chipnya semua nyatu banget! ', 'positive'),
         ('dua-dua nya cukup enak untuk pertama kali berkunjung', 'positive'),
         ('Very tasty Indonesian cuisine', 'positive'),
         ('The Nasi Cakalang, Nasi Limo, and Nasi Ayam Pecel are the must-try dishes...', 'positive'),
         ('Secara keseluruhan sih masih boleh lah dimsum di sini dijadikan sasaran untuk brunch atau ngemil iseng', 'positive'),
         ('dengan ciri khas makanan yang lezat dan kualitasnya bagus..', 'positive'),
         ('Shaokaonya enak, bumbunya pas dan dibakarnya juga pas ga terlalu kering..', 'positive'),
         ('very recommended..', 'positive'),
         ('Martabak Pecenongan 65A never disappoints me', 'positive'),
         ('Adonan tebal maupun yg tipis enak""! Topingnya dikasih melimpah', 'positive'),
         ('Good taste overall', 'positive'),
         ('Goreng-goreng enak, lumpia udang kulit tahu suprisingly enak...', 'positive'),
         ('Makanannya juga enak, gue pesen cumi dan bebek dengan nasi hainam super yummy!', 'positive'),
         ('Enak nih,  Chinese food nya', 'positive'),
         ('mantap nasi goreng seafood nya&#128077;', 'positive'),
         ('penasaran ma tuh rrsep nya ,   kaya ada harum kare nya gitu deh..', 'positive'),
         ('Nasi gorengnya enak dan gurih', 'positive'),
         ('Aku pesen steamboat spesial kuah tom yum rasanya enak seger sih kenyang bgt buat makan ber 3 tanpa nasi', 'positive'),
         ('Recommended deh', 'positive'),
         ('Sabar menunggu lama krn dori nya enak sekali', 'positive'),
         ('Paling suka pesan dengan Wedges potato! Ah i\'m in love with this kind of potato &#9825;', 'positive'),
         ('You can choose how will they cook it : butter cooked, sweet and sour, curry, or just boiled it', 'positive'),
         ('Suka sama kopinya, terutama red velvet ice latte-nya enak!', 'positive'),
         ('I love to eat bbq beef burger, very delicious !', 'positive'),
         ('the all day dining menu are pretty decent', 'positive'),
         ('Makanannya lumayan enak. Menunya banyak.', 'positive'),
         ('Overall rasanya enak, next time i\'ll come back', 'positive'),
         ('Nuttela latte nya enak lumayan kental dengan porsi mini, coffee vietnamnya so so lah..', 'positive'),
         ('singkong keju meski kejunya dikit tapi oke lah tertutupi sama tekstur singkongnya yang lembut', 'positive'),
         ('Potato wegess nya enak, recomended la..', 'positive'),
         ('Pilihan tepat klo mau makan steak enak', 'positive'),
         ('rasa maknyus..', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('WOW surprisingly enak enak lho!! Pizzanya apalagi! Truffle-nya pas nggak over powering, crustnya enak tipis tp ga begitu tipis', 'positive'),
         ('Spaghettinya enaaakk al dente dan seasoning garlic and pepper-nya pas', 'positive'),
         ('Honestly, ini uenak banget, kita sampe pesen 2x dan jadinya makan cuma itu doang', 'positive'),
         ('85% suit my taste for their menya gyutan don hehehe it really is my favorite', 'positive'),
         ('but the taste was not really bad, i love it too', 'positive'),
         ('great quality products with a lot of tasty treats to buy and take home, or even share with family/friends', 'positive'),
         ('Cake quality was extremely good', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive'),
         ('Rasanya ga ada amis2nya gt. Fresh sih. Ditambah sambal bangkok dan selada yg sangat amat yummy', 'positive')]
    return v


def food_neg():
    v = [('The food varieties arent that many', 'negative'),
         ('Yang agak ngga sreg mungkin cuma western foodnya, somehow berasa biasa aja', 'negative'),
         ('Porsinya sedikit', 'negative'),
         ('Rasanya biasa aja. Overall Tidak worth it', 'negative'),
         ('I wouldn\'t recommend their breakfast menu', 'negative'),
         ('pesen gue kue cubit tuna tapi kurang greget', 'negative'),
         ('pesen susu rasa greentea tapi rasa green tea nya kurang terasa', 'negative')]
    return v


def price_pos():
    v = [('the price is not worth anymore', 'positive'),
         ('Harga nya bersahabat banget', 'positive'),
         ('I always come here only for the roasted chicken, because the price isn\'t high at all', 'positive'),
         ('Price is super affordable', 'positive'),
         ('i can safely say that you get what u paid for, and that\'s a 5!', 'positive'),
         ('buat harga standar', 'positive'),
         ('Murah', 'positive'),
         ('this is my best pocket friendly place', 'positive'),
         ('harganya sangat terjangkau', 'positive'),
         ('Harga ga terlalu mahal, plus sering ad diskon..', 'positive'),
         ('very recommended..', 'positive'),
         ('Harganya juga pas! Pokoknya the best martabak maker deh', 'positive'),
         ('harga nya juga gak mahal', 'positive'),
         ('lumayan lg ada disc 50% juga hihihihi :D&#160;', 'positive'),
         ('Untuk harga standar buat kantong mahasiswi', 'positive'),
         ('harga pas di kantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga termasuk okelah untuk di lokasi daerah cikini/menteng', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive'),
         ('Harga pas dikantong..', 'positive')]
    return v


def price_neg():
    v = [('Decent price (used to be)', 'negative'),
         ('Untuk harga mungkin agak mahal ya', 'negative'),
         ('In overall this place is pricey', 'negative'),
         ('memang harga makanan disini mahal-mahal', 'negative'),
         ('Harganya mahal', 'negative'),
         ('as most of them are overpriced for the portion and quality of the food ', 'negative')]
    return v


def service_pos():
    v = [('kursinya lumayan banyak ada toilet nya juga..', 'positive'),
         ('also great service that gives you great vibe!', 'positive'),
         ('orang2 disini ramah banget bikin mau kesini teruus', 'positive'),
         ('pelayanan nya ramah banget dan enak untuk diajak ngobrol soal kopi', 'positive'),
         ('Dan service disini sopan banget', 'positive'),
         ('Serving staffnya ramah &amp; fast response', 'positive'),
         ('it\'s all about 5 star foods, ambience, &amp; service', 'positive'),
         ('The waiters are kind to us', 'positive'),
         ('mas nya mau nganter', 'positive'),
         ('Mas mas nya juga ramah', 'positive'),
         ('Plus mereka menampung kritik dan saran di instanya (@martabak65a) atau di contact personnya sendiri', 'positive'),
         ('pelayanannya cepet bgt', 'positive'),
         ('Recommended deh', 'positive'),
         ('Tapi walaupun selalu waiting list tp tidak butuh waktu lama sdh dapat tempat duduk', 'positive'),
         ('Pelayanan nya ramah', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('at first pelayanannya bagus cepet dan friendly', 'positive'),
         ('along with friendly customer service', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive'),
         ('Pelayanan cepat', 'positive')]
    return v


def service_neg():
    v = [('Gilak gue rasa utk servis msh hrs byk belajar deh, gak kyk td pelayannya gak peka', 'negative'),
         ('Masih kaku gt', 'negative'),
         ('Terus masa gue dah hampir 30menit lama gak ada satupun mknan yg dtg', 'negative'),
         ('service dan prosedur pelayanannya sih yg mesti jd concern, kliatan bgt blm ready', 'negative'),
         ('Ditambah pelayananannya lama, harus diingetin dulu baru dibikin', 'negative'),
         ('Selang 1 jam baru makanan diantar, padahal hanya mie kuah', 'negative'),
         ('Too bad for the slooooow service', 'negative'),
         ('VERY LONG service time', 'negative')]
    return v


def ambience_pos():
    v = [('I love the concept', 'positive'),
         ('also the nice place', 'positive'),
         ('I love the concept', 'positive'),
         ('suasana nya juga enak buat makan ramai2 gitu', 'positive'),
         ('Best place to date someone', 'positive'),
         ('Good ambiance nice interior', 'positive'),
         ('Pdhal tempatnya dah keren, luas bgt', 'positive'),
         ('Interiornya keren', 'positive'),
         ('Tempatnya enak, cozy, parkirannya pun lumayan luas', 'positive'),
         ('As you know Wargih ini selalu rame gapernah sepi', 'positive'),
         ('Great concept relatable with its name \'Marche\'', 'positive'),
         ('Good interior', 'positive'),
         ('Tempatnya jg unik bgt lucu bisa buat foto2 hehe', 'positive'),
         ('Nice place to chill with', 'positive'),
         ('try to come here at night its beautiful', 'positive'),
         ('perfect place to spend with family or lover', 'positive'),
         ('Perfect getaway', 'positive'),
         ('ambience is very cosy', 'positive'),
         ('Tempat nya enakk banget nyaman banget', 'positive'),
         ('Tempatnya gede banget, lavish, apalagi yang ada di sayap kiri keren banget buat foto2', 'positive'),
         ('it\'s all about 5 star foods, ambience, &amp; service', 'positive'),
         ('This place is nice', 'positive'),
         ('Well organized', 'positive'),
         ('The ambience of the restaurant is relaxing', 'positive'),
         ('A good place to get a short break during a stressfull day', 'positive'),
         ('Untuk tempat cukup nyaman walau kami merasa tinggi meja dan kursi kurang nyaman untuk makan dikarenakan meja yang pendek', 'positive'),
         ('A small but cozy culinary hideout in South Jakarta', 'positive'),
         ('Tempatnya bersih', 'positive'),
         ('Penyajiannya oke aka higenis', 'positive'),
         ('Great place! Tempatnya nyaman banget, spacious', 'positive'),
         ('Tempatnya enak, nyaman kursinya, walaupun agak kecil sih tp dekorasinya bagus', 'positive'),
         ('Recommended deh', 'positive'),
         ('tempatnya juga cozy dan gak berisik karena posisinya di pojokan', 'positive'),
         ('Love the ambience of this place', 'positive'),
         ('Apalagi yg outdoor, sejuk', 'positive'),
         ('This place isn\'t big but very cozy for me with nice music', 'positive'),
         ('Tempatnya luas sekali', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempatnya lumayan lucu ada indoor dan outdoor (smoking area)', 'positive'),
         ('Great place, lovely ambience', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive'),
         ('Tempat nya kecil ada indoor &amp; outdoor tapi lumayan buat kumpul2 sama temen2', 'positive')]
    return v


def ambience_neg():
    v = [('The only lack about garcon is their humid smoking area', 'negative'),
         ('diluasin lagi tempatnya untuk smoking area, is to small and hot :(', 'negative'),
         ('soalnya kursinya juga dikit terus gelap', 'negative'),
         ('Tempatnya sebenarnya besar, tapi penataannya nggak terlalu rapi dan ""fit-in"", apalagi di lantai 2 nya', 'negative'),
         ('Suasananya juga berisik', 'negative'),
         ('tapi kalau suka dengan suasana tenang, I don\'t recommend you to eat here', 'negative')]
    return v
